# [SERVICE]
#     Flush       1
#     Daemon      Off
#     Log_Level   info
#
# # Input: Read from a.txt
# [INPUT]
#     Name        tail
#     Path        /opt/fluent-bit/bin/a.txt
#     Tag         mylogs
#
# # Output 1: Write to b.txt
# # [OUTPUT]
# #     Name   file
# #     Match  mylogs
# #     Path   /opt/fluent-bit/bin/
# #     File   b.txt
#
# # Output 2: Print to stdout
# [OUTPUT]
#     Name        stdout
#     Match       mylogs
#
[SERVICE]
    Flush       1
    Daemon      Off
    Log_Level   info

[INPUT]
    Name        tail
    Path        /home/gm005/Log-Anomaly-Detection/backend/logs/healthcare_server.log
    Tag         mylogs

[OUTPUT]
    Name        stdout
    Match       mylogs
