[SERVICE]
    Flush       1
    Daemon      Off
    Log_Level   info

[INPUT]
    Name        tail
    Path        /home/gm005/Log-Anomaly-Detection/backend/logs/healthcare_server.log
    Tag         mylogs

[OUTPUT]
    Name        http
    Match       mylogs
    Host        127.0.0.1
    Port        5000
    URI         /ingest
    Format      json
